version: '3'
services:
  web:
    image: ellensu/nginx
    container_name: web
    networks:
     - nginx
    environment:
     - NODE_ENV:"stg"
    restart: on-failure
networks:
  nginx:
    driver: bridge